import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Skilly",
};

export default function TermsPage() {
  return (
    <div className="bg-secondary">
      <div className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold text-foreground">Terms of Service</h1>
        <p className="text-chart-3 text-sm mt-2">
          Last updated:{" "}
          {new Date().toLocaleDateString("en-US", {
            month: "long",
            year: "numeric",
          })}
        </p>

        <div className="mt-8 space-y-8 text-foreground/90">
          <section>
            <h2 className="text-xl font-semibold text-foreground">
              1. Acceptance
            </h2>
            <p className="mt-2 text-chart-3">
              By creating an account on Skilly, you agree to these terms. Skilly
              is an academic project built for demonstration purposes as part of
              a BS Computer Science thesis.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              2. The Service
            </h2>
            <p className="mt-2 text-chart-3">
              Skilly provides AI-generated career guidance based on information
              you provide. Career suggestions, skill gap analyses, and course
              recommendations are generated by an AI model and are intended as
              guidance only, not professional career counseling or a guarantee
              of employment outcomes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              3. Your Account
            </h2>
            <p className="mt-2 text-chart-3">
              You are responsible for the accuracy of the information you
              provide and for keeping your login credentials secure. You must be
              able to provide a valid email address to use Skilly.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              4. Acceptable Use
            </h2>
            <p className="mt-2 text-chart-3">You agree not to:</p>
            <ul className="list-disc pl-6 mt-2 text-chart-3 space-y-1">
              <li>Provide false information when creating an account</li>
              <li>Attempt to access another user&apos;s account or data</li>
              <li>
                Use the platform in any way that disrupts its normal operation
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              5. AI-Generated Content
            </h2>
            <p className="mt-2 text-chart-3">
              Career recommendations, skill gap notes, and course suggestions
              are generated automatically by a third-party AI model based on the
              profile data you provide. This content may be inaccurate or
              incomplete and should not be relied upon as the sole basis for
              career decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              6. Account Termination
            </h2>
            <p className="mt-2 text-chart-3">
              You may delete your account at any time from Settings, which
              permanently removes your data. We reserve the right to suspend
              accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              7. No Warranty
            </h2>
            <p className="mt-2 text-chart-3">
              Skilly is provided &quot;as is,&quot; as an academic project,
              without warranty of any kind, express or implied.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              8. Contact
            </h2>
            <p className="mt-2 text-chart-3">
              Questions about these terms can be sent through the{" "}
              <a href="/contact" className="text-primary font-medium">
                Contact page
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
